name: iris-parser
version: 0.1.0
github: "morpheus-graphql/iris"
license: MIT
author: "Daviti Nalchevanidze"
category: web, language
synopsis: Iris Parser
maintainer: "d.nalchevanidze@gmail.com"
copyright: "(c) 2021 Daviti Nalchevanidze"
license-file: LICENSE
description: GraphQL like language

extra-source-files:
  - changelog.md
  - README.md

data-files:
  - test/**/*.gql
  - test/**/*.json

dependencies:
  - base                  >= 4.7       && <  5
  - bytestring            >= 0.10.4    && <  0.11
  - text                  >= 1.2.3.0   && <  1.3
  - megaparsec            >= 7.0.0     && <  10.0.0
  - aeson                 >= 1.4.4.0   && <= 1.6
  - unordered-containers  >= 0.2.8.0   && <  0.3
  - transformers          >= 0.3.0.0   && <  0.6
  - scientific            >= 0.3.6.2   && <  0.4
  - vector                >= 0.12.0.1  && <  0.13
  - template-haskell      >= 2.0       && <= 3.0
  - th-lift-instances     >= 0.1.1     && <= 0.3
  - hashable              >= 1.0.0
  - mtl                   >= 2.0       && <= 3.0
  - relude                >= 0.3.0
  - containers            >= 0.4.2.1   && <  0.7

library:
  source-dirs: src
  exposed-modules:
    - Data.Mergeable.Utils
    - Language.Iris
    - Language.Iris.Types.Internal.AST
    - Language.Iris.Types
    - Language.Iris.Error
  ghc-options: -Wall

tests:
  iris-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - iris-parser
      - morpheus-graphql-tests         >= 0.18.0        && <  0.19.0
      - tasty
      - tasty-hunit
      - aeson
      - directory >= 1.0
      - relude    >= 0.3.0
