name: examples-iris-app
version: 0.1.0
github: "nalchevanidze/iris-app"
license: MIT
author: "Daviti Nalchevanidze"
category: web, graphql
synopsis: Morpheus GraphQL App
maintainer: "d.nalchevanidze@gmail.com"
copyright: "(c) 2019 Daviti Nalchevanidze"
description: Iris App

extra-source-files:
  - README.md

data-files:
  - test/**/*.gql

dependencies:
  - base         >= 4.7       && <  5
  - iris-parser
  - iris-app
  - bytestring   >= 0.10.4    && <  0.11
  - relude       >= 0.3.0
  - aeson
  - scotty


executables:
  iris-app:
    main: Main.hs
    source-dirs: src
    ghc-options: -Wall
